version: '3'
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper_dataenv
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: apache/nifi:latest
    container_name: nifi_docker
    ports:
      - 8040:8080
      - 8041:8081
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
    volumes:
        - ./data_in:/home/data_in
        - ./data_out:/home/data_out


  jupyter-notebook:
    image:  jupyter/minimal-notebook:latest
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data_in:/home/data_in

    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN : "jup123"

    ports:
      - 8882:8888
    container_name:   de-jupyter

    links:
      - nifi


